FROM python:3.9-slim

WORKDIR /app

# Enable unbuffered logging
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create a non-root user
RUN groupadd -g 10002 hivemind && \
    useradd -u 10002 -g hivemind -s /bin/bash -m hivemind

COPY hive_mind_server.py .
COPY cert.pem .
COPY key.pem .

# Ensure ownership for the new user
RUN chown -R hivemind:hivemind /app

USER hivemind

CMD ["python", "hive_mind_server.py"]
