[rabbithole]
enabled = true
port = 21,22,2121,2222
filter = rabbithole-filter
logpath = /path/to/your/RabbitHole/logs/alerts.log
maxretry = 1
bantime = 1h
findtime = 600
action = iptables-multiport[name=rabbithole, port="21,22,2121,2222", protocol=tcp]
